name: Update Snake

on:
  push:
    branches:
      - main

jobs:
  update-snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
